Q0 pipeline
navikt/soknadsarkiverer pull request #22
Opened 2020-09-08 06:59 UTC by nils-arne

SD-1108 - OIDC mot arkivet.

2020-09-08 11:42 UTC, sjoblomjsqueed requested changes
Meget bra jobbet! Et par kommentarer bare

2020-09-09 09:24 UTC, nils-arne commented on .nais/preprod-default.yml
> +    - name: TOKENENDPOINTURL
Den skal bort. Dette er lagt inn i Vault.

2020-09-09 09:38 UTC, nils-arne commented on .nais/preprod-q1.yml
> +      value: https://tjenester-q1.nav.no/soknadsfillager
Gått gjennom alle Yml filene og satt filestorage_host på formen: https://soknadsfillagerxxx.nais.preprod.local

2020-09-09 09:41 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/arkivservice/JournalpostClient.kt
> +		if (responseEntity != null) {
Fjernet

2020-09-09 09:49 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/arkivservice/converter/MessageConverter.kt
> +	return DokumentVariant(variant.getFilnavn(), if (variant.getFiltype().equals("PDF/A")) "PDFA" else variant.getFiltype(), attachedFile[0].fil!!, variant.getVariantformat())
Synes at det hører til her da det er Joark-APIet som forutsetter at vi skal angi variant type som PDFA, PDF, JSON, ......

2020-09-09 09:50 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/config/ApplicationConfig.kt
> +	"JOARK_URL" to "/joark/save", // /swagger-ui.html#/arkiver-og-journalfoer-rest-controller/opprettJournalpostUsingPOST
Fjernet

2020-09-09 09:54 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/config/ApplicationConfig.kt
> +	"GRANTTYPE" to "client_credentials",
Slettet

2020-09-09 09:55 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/config/ApplicationConfig.kt
> +	"SCOPES" to "openid",
Slettet

2020-09-09 09:55 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/config/ApplicationConfig.kt
> +	"CLIENTAUTHMETHOD" to "client_secret_basic"
Slettet

2020-09-09 09:57 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/config/ArchiveRestTemplateTestConfig.kt
> +		logger.info("Token tokenEndpointUrl= ${properties?.tokenEndpointUrl}")
Nei, brukes bare i forbindelse OIDC.

2020-09-09 10:00 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/config/ArchiveRestTemplateTestConfig.kt
> +		return restTemplate
Den har ikke basicauth som RestTemplate

2020-09-09 10:02 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/config/JournalpostClientConfig.kt
> +	fun journalpostClient() = JournalpostClient(appConfiguration, restTemplate)
Kan være at du har rett. Du kan kanskje forsøke?

2020-09-09 10:03 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/service/ArchiverService.kt
> +			.joinToString(",")
Fjernet

2020-09-09 10:05 UTC, nils-arne commented on src/main/kotlin/no/nav/soknad/arkivering/soknadsarkiverer/service/fileservice/FilestorageService.kt
> +		logger.info("Forsøker å kalle ${url} med username=${username} og sharedPassword=${tmp}")
Fjernet

2020-09-14 08:00 UTC, sturleh reviewed
Jeg tror det vil være bra med en go refakturering av filer + klasser og variabel navn her, vi skriver oos her bort fra domenebeskrivelsene på norsk/NAVSK og mer generell engelsk.

2020-09-22 12:15 UTC, sjoblomjsqueed approved these changes

2020-09-24 09:25 UTC, merged